/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Panther"
include(":panther-annotations")
include(":panther-placeholders")
include(":panther-containers")
include(":panther-common")
include(":panther-paste")
