/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("panther.java-conventions")
    id("panther.guava-conventions")
    id("panther.publish-conventions")
    id("panther.external-shadow-conventions")
}

dependencies {
    // Expose "panther-common" to consumers
    api(project(":panther-common"))
}

description = "panther-paste"
