/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("panther.java-conventions")
    id("panther.publish-conventions")
    id("panther.external-shadow-conventions")
}

dependencies {
    testImplementation(libs.guava)
    // Expose "panther-common" to consumers
    api(project(":panther-common"))
}

description = "A library for working with Pastebin and hastebin"
