# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test-build:
    name: "Test build"
    uses: the-h-team/workflows/.github/workflows/gradle.yml@95420c133a5a8607985e120aba15268ba3a3534a
    with:
      gradle_args: "build shadowJar"
  dispatched-deploy:
    name: "Deploy to GitHub Packages"
    needs: test-build
    if: github.event_name == 'workflow_dispatch'
    uses: the-h-team/workflows/.github/workflows/gradle.yml@95420c133a5a8607985e120aba15268ba3a3534a
    with:
      gradle_args: "shadowJar publish"
      cache_save: false
