# This workflow will build and publish the project with Gradle

name: Gradle Publish

on:
  # This workflow is only run manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: A custom version string
        required: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Override version
        if: ${{ inputs.version != '' }}
        run: |
          echo "ORG_GRADLE_PROJECT_version=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.nexus_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.nexus_password }}
          ORG_GRADLE_PROJECT_base64SigningKey: ${{ secrets.base64SigningKey }}
          ORG_GRADLE_PROJECT_signingKeyPassphrase: ${{ secrets.signingKeyPassphrase }}
        with:
          arguments: publishToSonatype closeSonatypeStagingRepository
